os: linux
sudo: false
language: python

install:
  - pip install tornado
  - pip install bcrypt
  - pip install jinja2

branches:
  only:
    - master
    - develop

script:
  - python -m unittest discover

notifications:
  email: false